import type { IngredientCategory } from '../types'

export const defaultCategoryCache: Record<string, IngredientCategory> = {
  'ground beef': 'meat',
  'roma tomatoes': 'produce',
  'baby spinach': 'produce',
  'tortillas': 'bakery',
  'sour cream': 'dairy',
  'eggs': 'dairy',
  'yellow onion': 'produce',
  'garlic': 'produce',
  'bell peppers': 'produce',
  'avocados': 'produce',
  'limes': 'produce',
  'broccoli': 'produce',
  'carrots': 'produce',
  'russet potatoes': 'produce',
  'bananas': 'produce',
  'whole milk': 'dairy',
  'shredded cheddar': 'dairy',
  'parmesan': 'dairy',
  'greek yogurt': 'dairy',
  'unsalted butter': 'dairy',
  'chicken breast': 'meat',
  'bacon': 'meat',
  'salmon fillets': 'meat',
  'ground turkey': 'meat',
  'sandwich bread': 'bakery',
  'bagels': 'bakery',
  'frozen peas': 'frozen',
  'frozen mixed berries': 'frozen',
  'vanilla ice cream': 'frozen',
  'jasmine rice': 'pantry',
  'spaghetti': 'pantry',
  'olive oil': 'pantry',
  'canned black beans': 'pantry',
  'marinara sauce': 'pantry',
  'kosher salt': 'pantry',
  'all-purpose flour': 'pantry',
  'granulated sugar': 'pantry',
  'dark chocolate bar': 'other',
  'coffee beans': 'other',
}
