import type { KitchenData } from '../types'
import { COUNT_UNIT } from './kitchen-constants'

export const defaultKitchenState: KitchenData = {
  ingredients: [
    {
      id: 'ing-ground-beef',
      name: 'Ground beef',
      category: 'meat',
      quantity: { amount: 1, unit: 'lb' },
      expiresAtIso: '2026-07-21T09:00:00.000Z',
      addedAtIso: '2026-07-18T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-roma-tomatoes',
      name: 'Roma tomatoes',
      category: 'produce',
      quantity: { amount: 6, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-22T09:00:00.000Z',
      addedAtIso: '2026-07-17T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-baby-spinach',
      name: 'Baby spinach',
      category: 'produce',
      quantity: { amount: 1, unit: 'bag' },
      expiresAtIso: '2026-07-24T09:00:00.000Z',
      addedAtIso: '2026-07-19T09:00:00.000Z',
      substitutions: ['frozen spinach', 'kale'],
    },
    {
      id: 'ing-tortillas',
      name: 'Tortillas',
      category: 'bakery',
      quantity: { amount: 12, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-22T09:00:00.000Z',
      addedAtIso: '2026-07-18T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-sour-cream',
      name: 'Sour cream',
      category: 'dairy',
      quantity: { amount: 1, unit: 'tub' },
      expiresAtIso: '2026-07-23T09:00:00.000Z',
      addedAtIso: '2026-07-16T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-eggs',
      name: 'Eggs',
      category: 'dairy',
      quantity: { amount: 6, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-24T09:00:00.000Z',
      addedAtIso: '2026-07-17T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-yellow-onion',
      name: 'Yellow onion',
      category: 'produce',
      quantity: { amount: 3, unit: COUNT_UNIT },
      expiresAtIso: '2026-08-02T09:00:00.000Z',
      addedAtIso: '2026-07-12T09:00:00.000Z',
      substitutions: ['shallots'],
    },
    {
      id: 'ing-garlic',
      name: 'Garlic',
      category: 'produce',
      quantity: { amount: 2, unit: 'head' },
      expiresAtIso: '2026-08-07T09:00:00.000Z',
      addedAtIso: '2026-07-08T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-bell-peppers',
      name: 'Bell peppers',
      category: 'produce',
      quantity: { amount: 3, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-25T09:00:00.000Z',
      addedAtIso: '2026-07-18T09:00:00.000Z',
      substitutions: ['poblano peppers'],
    },
    {
      id: 'ing-avocados',
      name: 'Avocados',
      category: 'produce',
      quantity: { amount: 2, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-23T09:00:00.000Z',
      addedAtIso: '2026-07-19T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-limes',
      name: 'Limes',
      category: 'produce',
      quantity: { amount: 4, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-27T09:00:00.000Z',
      addedAtIso: '2026-07-17T09:00:00.000Z',
      substitutions: ['lemons'],
    },
    {
      id: 'ing-broccoli',
      name: 'Broccoli',
      category: 'produce',
      quantity: { amount: 1, unit: 'head' },
      expiresAtIso: '2026-07-19T09:00:00.000Z',
      addedAtIso: '2026-07-14T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-carrots',
      name: 'Carrots',
      category: 'produce',
      quantity: { amount: 1, unit: 'bag' },
      expiresAtIso: '2026-07-31T09:00:00.000Z',
      addedAtIso: '2026-07-10T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-russet-potatoes',
      name: 'Russet potatoes',
      category: 'produce',
      quantity: { amount: 5, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-31T09:00:00.000Z',
      addedAtIso: '2026-07-01T09:00:00.000Z',
      substitutions: ['yukon gold potatoes'],
    },
    {
      id: 'ing-bananas',
      name: 'Bananas',
      category: 'produce',
      quantity: { amount: 6, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-20T09:00:00.000Z',
      addedAtIso: '2026-07-19T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-whole-milk',
      name: 'Whole milk',
      category: 'dairy',
      quantity: { amount: 1, unit: 'gallon' },
      expiresAtIso: '2026-07-28T09:00:00.000Z',
      addedAtIso: '2026-07-18T09:00:00.000Z',
      substitutions: ['oat milk', 'almond milk'],
    },
    {
      id: 'ing-shredded-cheddar',
      name: 'Shredded cheddar',
      category: 'dairy',
      quantity: { amount: 1, unit: 'bag' },
      expiresAtIso: '2026-08-04T09:00:00.000Z',
      addedAtIso: '2026-07-14T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-parmesan',
      name: 'Parmesan',
      category: 'dairy',
      quantity: { amount: 1, unit: 'wedge' },
      expiresAtIso: '2026-08-19T09:00:00.000Z',
      addedAtIso: '2026-07-05T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-greek-yogurt',
      name: 'Greek yogurt',
      category: 'dairy',
      quantity: { amount: 1, unit: 'tub' },
      expiresAtIso: '2026-07-29T09:00:00.000Z',
      addedAtIso: '2026-07-15T09:00:00.000Z',
      substitutions: ['plain yogurt'],
    },
    {
      id: 'ing-butter',
      name: 'Unsalted butter',
      category: 'dairy',
      quantity: { amount: 1, unit: 'lb' },
      expiresAtIso: '2026-08-30T09:00:00.000Z',
      addedAtIso: '2026-07-01T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-chicken-breast',
      name: 'Chicken breast',
      category: 'meat',
      quantity: { amount: 2, unit: 'lb' },
      expiresAtIso: '2026-07-21T09:00:00.000Z',
      addedAtIso: '2026-07-19T09:00:00.000Z',
      substitutions: ['chicken thighs'],
    },
    {
      id: 'ing-bacon',
      name: 'Bacon',
      category: 'meat',
      quantity: { amount: 1, unit: 'pack' },
      expiresAtIso: '2026-07-18T09:00:00.000Z',
      addedAtIso: '2026-07-11T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-salmon',
      name: 'Salmon fillets',
      category: 'meat',
      quantity: { amount: 2, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-21T09:00:00.000Z',
      addedAtIso: '2026-07-19T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-ground-turkey',
      name: 'Ground turkey',
      category: 'meat',
      quantity: { amount: 1, unit: 'lb' },
      expiresAtIso: '2026-07-20T09:00:00.000Z',
      addedAtIso: '2026-07-17T09:00:00.000Z',
      substitutions: ['ground chicken'],
    },
    {
      id: 'ing-sandwich-bread',
      name: 'Sandwich bread',
      category: 'bakery',
      quantity: { amount: 1, unit: 'loaf' },
      expiresAtIso: '2026-07-22T09:00:00.000Z',
      addedAtIso: '2026-07-16T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-bagels',
      name: 'Bagels',
      category: 'bakery',
      quantity: { amount: 6, unit: COUNT_UNIT },
      expiresAtIso: '2026-07-21T09:00:00.000Z',
      addedAtIso: '2026-07-16T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-frozen-peas',
      name: 'Frozen peas',
      category: 'frozen',
      quantity: { amount: 1, unit: 'bag' },
      expiresAtIso: '2026-09-18T09:00:00.000Z',
      addedAtIso: '2026-06-20T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-frozen-berries',
      name: 'Frozen mixed berries',
      category: 'frozen',
      quantity: { amount: 1, unit: 'bag' },
      expiresAtIso: '2026-09-13T09:00:00.000Z',
      addedAtIso: '2026-06-15T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-vanilla-ice-cream',
      name: 'Vanilla ice cream',
      category: 'frozen',
      quantity: { amount: 1, unit: 'tub' },
      expiresAtIso: '2026-09-29T09:00:00.000Z',
      addedAtIso: '2026-07-01T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-jasmine-rice',
      name: 'Jasmine rice',
      category: 'pantry',
      quantity: { amount: 2, unit: 'lb' },
      expiresAtIso: null,
      addedAtIso: '2026-06-01T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-spaghetti',
      name: 'Spaghetti',
      category: 'pantry',
      quantity: { amount: 1, unit: 'box' },
      expiresAtIso: null,
      addedAtIso: '2026-06-01T09:00:00.000Z',
      substitutions: ['penne', 'fettuccine'],
    },
    {
      id: 'ing-olive-oil',
      name: 'Olive oil',
      category: 'pantry',
      quantity: { amount: 1, unit: 'bottle' },
      expiresAtIso: null,
      addedAtIso: '2026-05-10T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-black-beans',
      name: 'Canned black beans',
      category: 'pantry',
      quantity: { amount: 2, unit: COUNT_UNIT },
      expiresAtIso: null,
      addedAtIso: '2026-06-10T09:00:00.000Z',
      substitutions: ['canned pinto beans'],
    },
    {
      id: 'ing-marinara-sauce',
      name: 'Marinara sauce',
      category: 'pantry',
      quantity: { amount: 1, unit: 'jar' },
      expiresAtIso: null,
      addedAtIso: '2026-06-25T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-kosher-salt',
      name: 'Kosher salt',
      category: 'pantry',
      quantity: { amount: 1, unit: 'box' },
      expiresAtIso: null,
      addedAtIso: '2026-01-05T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-flour',
      name: 'All-purpose flour',
      category: 'pantry',
      quantity: { amount: 5, unit: 'lb' },
      expiresAtIso: null,
      addedAtIso: '2026-05-01T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-sugar',
      name: 'Granulated sugar',
      category: 'pantry',
      quantity: { amount: 4, unit: 'lb' },
      expiresAtIso: null,
      addedAtIso: '2026-05-01T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-dark-chocolate',
      name: 'Dark chocolate bar',
      category: 'other',
      quantity: { amount: 2, unit: COUNT_UNIT },
      expiresAtIso: null,
      addedAtIso: '2026-06-15T09:00:00.000Z',
      substitutions: [],
    },
    {
      id: 'ing-coffee-beans',
      name: 'Coffee beans',
      category: 'other',
      quantity: { amount: 1, unit: 'bag' },
      expiresAtIso: null,
      addedAtIso: '2026-07-05T09:00:00.000Z',
      substitutions: [],
    },
  ],
  recipes: [
    {
      id: 'rec-taco-night',
      name: 'Taco night',
      color: '#e05252',
      servings: 4,
      cookingThisWeek: true,
      notes:
        'Char the tortillas straight on the flame — about 10 seconds a side.',
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-ground-beef' },
          needed: { amount: 1, unit: 'lb' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-roma-tomatoes' },
          needed: { amount: 6, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-tortillas' },
          needed: { amount: 12, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-sour-cream' },
          needed: { amount: 1, unit: 'tub' },
        },
      ],
    },
    {
      id: 'rec-sat-frittata',
      name: 'Sat. frittata',
      color: '#e8a33d',
      servings: 2,
      cookingThisWeek: true,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-baby-spinach' },
          needed: { amount: 1, unit: 'bag' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-eggs' },
          needed: { amount: 6, unit: COUNT_UNIT },
        },
      ],
    },
    {
      id: 'rec-green-smoothies',
      name: 'Green smoothies',
      color: '#4caf50',
      servings: 2,
      cookingThisWeek: false,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-baby-spinach' },
          needed: { amount: 0.5, unit: 'bag' },
        },
      ],
    },
    {
      id: 'rec-sunday-roast',
      name: 'Sunday roast chicken',
      color: '#c2703d',
      servings: 4,
      cookingThisWeek: true,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-chicken-breast' },
          needed: { amount: 2, unit: 'lb' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-yellow-onion' },
          needed: { amount: 1, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-carrots' },
          needed: { amount: 4, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-russet-potatoes' },
          needed: { amount: 4, unit: COUNT_UNIT },
        },
      ],
    },
    {
      id: 'rec-turkey-stir-fry',
      name: 'Turkey veggie stir-fry',
      color: '#3d8f5b',
      servings: 3,
      cookingThisWeek: false,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-ground-turkey' },
          needed: { amount: 1, unit: 'lb' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-bell-peppers' },
          needed: { amount: 2, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-broccoli' },
          needed: { amount: 1, unit: 'head' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-jasmine-rice' },
          needed: { amount: 2, unit: 'cup' },
        },
      ],
    },
    {
      id: 'rec-bacon-toast',
      name: 'Bacon avocado toast',
      color: '#d9a441',
      servings: 2,
      cookingThisWeek: true,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-bacon' },
          needed: { amount: 4, unit: 'slice' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-sandwich-bread' },
          needed: { amount: 2, unit: 'slice' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-avocados' },
          needed: { amount: 1, unit: COUNT_UNIT },
        },
      ],
    },
    {
      id: 'rec-salmon-bowl',
      name: 'Salmon & rice bowl',
      color: '#4a90d9',
      servings: 2,
      cookingThisWeek: false,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-salmon' },
          needed: { amount: 2, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-jasmine-rice' },
          needed: { amount: 1, unit: 'cup' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-limes' },
          needed: { amount: 1, unit: COUNT_UNIT },
        },
      ],
    },
    {
      id: 'rec-marinara-pasta',
      name: 'Marinara pasta night',
      color: '#b23b3b',
      servings: 4,
      cookingThisWeek: false,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-spaghetti' },
          needed: { amount: 1, unit: 'box' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-marinara-sauce' },
          needed: { amount: 1, unit: 'jar' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-parmesan' },
          needed: { amount: 2, unit: 'oz' },
        },
      ],
    },
    {
      id: 'rec-weekend-pancakes',
      name: 'Weekend pancakes',
      color: '#e8c34d',
      servings: 4,
      cookingThisWeek: false,
      ingredients: [
        {
          source: { kind: 'kitchen', ingredientId: 'ing-eggs' },
          needed: { amount: 2, unit: COUNT_UNIT },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-whole-milk' },
          needed: { amount: 1, unit: 'cup' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-flour' },
          needed: { amount: 2, unit: 'cup' },
        },
        {
          source: { kind: 'kitchen', ingredientId: 'ing-butter' },
          needed: { amount: 2, unit: 'tbsp' },
        },
      ],
    },
  ],
}
