import type { IngredientCategory } from '../types'

export const CATEGORY_KEYWORDS: Record<IngredientCategory, string[]> = {
  produce: [
    'spinach',
    'tomato',
    'lettuce',
    'kale',
    'onion',
    'garlic',
    'cilantro',
    'basil',
    'carrot',
    'potato',
    'apple',
    'banana',
    'lemon',
    'lime',
    'avocado',
    'broccoli',
    'cucumber',
    'mushroom',
    'bell pepper',
    'ginger',
    'berries',
  ],
  dairy: [
    'milk',
    'cheese',
    'yogurt',
    'butter',
    'cream',
    'parmesan',
    'pecorino',
    'mozzarella',
    'egg',
  ],
  meat: [
    'beef',
    'chicken',
    'pork',
    'bacon',
    'sausage',
    'salmon',
    'fish',
    'turkey',
    'ham',
    'shrimp',
  ],
  bakery: ['bread', 'tortilla', 'bagel', 'baguette', 'bun'],
  frozen: ['frozen'],
  pantry: [
    'pasta',
    'spaghetti',
    'rice',
    'flour',
    'sugar',
    'salt',
    'pepper',
    'oil',
    'vinegar',
    'beans',
    'lentils',
    'stock',
    'sauce',
    'noodle',
  ],
  other: [],
}

export const DEFAULT_EXPIRY_DAYS: Record<IngredientCategory, number | null> = {
  produce: 5,
  dairy: 7,
  meat: 3,
  bakery: 4,
  frozen: 90,
  pantry: null,
  other: null,
}

export const EXPIRY_PRESETS_DAYS = [3, 5, 7]

export const COUNT_UNIT = 'x'
